@startuml
skinparam classAttributeIconSize 0



enum Niveau <<enumeration >> {
  1
  2
  3
}

enum Couleur <<enumeration >> {
  Blanc
  Vert
  Perle
  Bleu
  Or
  Rouge
  Noir
}

class Jeton {
  couleur : Couleur
}

enum Capacite <<enumeration >> {
  Rejouer
  Prendre_privilege
  Prendre_jeton_adversaire
  Prendre_jeton_plateau
  Cameleon
}

' struct TupleIntJeton {
'   nombre : int
'   type_jeton : Jeton
' }

class SplendorDuel {

  + lancerPartie() : void
  + finirPartie(): void
}

note bottom of Joueur : privilege entre 0 et 3

class Joueur {
  - nom : string
  - privilege :int 
  '- {field} jetons : List[TupleIntJeton]

  + reserverCarte(Carte carte)
  + acheterCarte()
  + ajouterJeton(Jeton jeton)
  + depenserJeton(Jeton jeton)
  + utiliserPrivilege(privilege)
}

note bottom of CarteJoaillerie : point de prestige entre 0 et 4\ncouronne entre 0 et 2
class CarteJoaillerie <<abstract>>{
  - niveau : Niveau
  - bonus : Couleur
  - point_de_prestige : int
  - capacite : Capacite
  '- {field} cout : List[TupleIntJeton]
  - couronne : int
}

note bottom of CarteRoyale :  point de prestige 2 ou 3\ncouronnes nécessaire entre 3 ou 6
class CarteRoyale {
  - point_de_prestige : int
  - capacite : Capacite
  - couronne_necessaire : int
}

class SacJeton{
  '- {field} jetons : List[TupleIntJeton]

}


class Plateau{
}

class CoordonneeJeton{
  x : int
  y : int
}

class LigneDeCarte{
  - niveau : Niveau
}



SplendorDuel "1" -- "2" Joueur : < joue
SplendorDuel "1" -- "1" Plateau : se joue sur >
SplendorDuel "1" -- "1" SacJeton : se joue avec >
SplendorDuel "1" -- "*" CarteJoaillerie : se joue avec >
SplendorDuel "1" -- "4" CarteRoyale : se joue avec >
SplendorDuel "1" -- "3" LigneDeCarte : se joue avec >

LigneDeCarte "3" -- "*" CarteJoaillerie : < est empilée
LigneDeCarte "3" -- "*" CarteJoaillerie : < est découverte

Jeton "0..10" -- "0..1" Joueur : possède <
Jeton "0..25" -- "0..1" SacJeton : contient <
Jeton "0..25" -- "1" Plateau : est posé sur >

CoordonneeJeton "0..25" --  "1" Plateau
CoordonneeJeton "0..1" -- "1" Jeton

Joueur "0..1" -- "0..*" CarteJoaillerie : possède >
' CarteJoaillerie <|-- CarteNiveau1
' CarteJoaillerie <|-- CarteNiveau2
' CarteJoaillerie <|-- CarteNiveau3

Joueur "0..1" -- "0..2" CarteRoyale : possède >


@enduml



